### PR TITLE
Fix #55: Hide Bottom Navigation on Contact List Fragment

### LINKED ISSUE #55: Debug the transition between fragments navigation using bottom navigation
Issue:

https://user-images.githubusercontent.com/75999921/161398114-d16e9257-a312-4f38-baf8-d780facb9679.mp4

### PR DESCRIPTION
**Pull request by MohitGupta121**
Fixed #55 
Debug the transition between fragments navigation using bottom navigation

Below is the Screen Recoding of Changes:- 

https://user-images.githubusercontent.com/76530270/163543050-d252b04e-6758-444c-b2b7-5464f69adedd.mp4

### CODE REVIEW

**Comment by MohitGupta121** [comment]
@yellowHatpro can you please review this PR for issue #55

**Review by yellowHatpro — APPROVED** [review]
Yeah now it looks better

**Comment by MohitGupta121** [comment]
> Yeah now it looks better

Thanks you 

Can you please assign this PR to me 
Add Lables Level and GSsoc 
As per gsssoc 2022

**Comment by MohitGupta121** [comment]
@yellowHatpro please add lables on this PR please

**Pull request merged**
